packages:
  - "apps/*"
  - "packages/*"

catalogs:
  angular-20:
    "@analogjs/vite-plugin-angular": ^1.19.1
    "@analogjs/vitest-angular": ^1.19.1
    "@angular/common": ^20.1.3
    "@angular/compiler": ^20.1.3
    "@angular/core": ^20.1.3
    "@angular/forms": ^20.1.3
    "@angular/platform-browser": ^20.1.3
    "@angular/platform-browser-dynamic": ^20.1.3
    "@angular/router": ^20.1.3
    "@angular/build": ^20.1.3
    "@angular/compiler-cli": ^20.1.3
  vite-7:
    vite: ^7.0.6
    vitest: ^3.2.4
    "@module-federation/vite": ^1.7.1

